### ISSUE TITLE
v5.9 update bugs

### ISSUE THREAD

**Issue by Ben-Maxfield** [matt-cook/kiosk#158]
As of 5.9.2 release we have had issues on Asus Chromebits with the cache not clearing for the app when restarted etc.

As 5.9.2 included changes to the HTML/CSS this has caused the page to only load the URL characters as tabs on a black background instead of actual page contents. To fix this we can clear the cache on the admin panel, but without a manual cache clear on admin panel the kiosk app is broken for us.

This is an issue as we have many Chromebits across the country running this app to display images, which now, do not work. 

When changing HTML/CSS would be good to force a cache clear along with update somehow.

![chromebitissue](https://cloud.githubusercontent.com/assets/24387828/20884453/3e8f9aa2-bae3-11e6-9d42-2c963a6c4bbf.png)

**Comment by welrachid** [comment]
We have exactly same issue.
Also devices remotely and all are blanks.

**Comment by nithiz** [comment]
Same here, i thought it had to do with reconfiguring the url's.

**Comment by allencoin** [comment]
Having the same issue. Is there any temporary fix or does it have the same problem with each refresh?

**Comment by nithiz** [comment]
@allencoin @welrachid @Ben-Maxfield  The only solution i could think of (if you're using managed devices) is to clone the 5.9.2 tag and release it as a separate Chrome App. In your managed device admin you would then change the kiosk app to your own app (the 5.9.2 one). My only concern with this is that it maybe causes all configuration to be lost. This is something you would have to gamble on in that case. DISCLAIMER: I have not tried this so don't take my word for it.

**Comment by Ben-Maxfield** [comment]
@nithiz I agree that reverting to previous stable version and re-release would work, but ofc I have no ability to change the app on our devices remotely so it will not work for my circumstance. Good idea though, hope it helps others

**Comment by nithiz** [comment]
@Ben-Maxfield  If you're working with "managed devices" (meaning that you have your devices configured in an enterprise setting) you can trough the Google Admin interface. More info: https://support.google.com/chrome/a/answer/188446?hl=en&ref_topic=6242757. But ofcourse if that's not the case you're out of luck :(

**Comment by Ben-Maxfield** [comment]
@nithiz @allencoin  @welrachid 

update from Matt Cook via email:

Hi Ben, thanks for the detailed report! I've released v5.9.3 which addresses a issue with the URL handling. Please let me know that resolves the problem for you.

5.9.0 has been a pretty rocky release. I'm evaluating additional guardrails on production updates to avoid this sort of problem in the future.

**Comment by welrachid** [comment]
Hi, I was also working on a fix, and we made same solution where url was expected to be array, but was string. In chrome extension webshop it is still showing 5.9.2 version

**Comment by Ben-Maxfield** [comment]
@welrachid  "In chrome extension webshop it is still showing 5.9.2 version"

Does indeed, I just copied the email over as soon as I received it, may take time to propagate over shop or something, not 100% on how google push updates out etc, hopefully it will resolve soon though

**Comment by welrachid** [comment]
@Ben-Maxfield  hi, i just rechecked out and reproduced the "error" in 5.9.2 and can confirm that it is solved in 5.9.3

**Comment by Ben-Maxfield** [comment]
@welrachid Perfect, thank you, haven't been able to test yet myself, I will email Matt back about this thread and let him know. Will close this once confirmed my side also.

**Comment by nithiz** [comment]
@Ben-Maxfield Great news! I'll try to update my clients now.

**Comment by Ben-Maxfield** [comment]
Store is now 5.9.3 (y)

**Comment by welrachid** [comment]
@Ben-Maxfield you can reproduce it by opening the console and typing in

`chrome.storage.local.set({'url': 'https://www.google.com'});`

**Comment by welrachid** [comment]
The real question is now how i make sure all my clients boxes are updated? is it done automatically? or do i have to "restart" the chromebox?

**Comment by Ben-Maxfield** [comment]
@welrachid chrome will auto update all extensions automatically provided the manifest from download hasn't been modified (they default to auto download updates).

restarting OS or browser won't force it though, the update check occurs every 5 hours or so, but some people claim it takes up to 48 hours... Issue may be fixed but might have to put up with it for a while, unless you can start their chrome application with the extensions-update-frequency param.

For anyone else: Go to chrome://extensions, tick the Developer mode checkbox at the top right, then press the Update Extensions Now button

**Comment by nithiz** [comment]
@welrachid  If you're using managed devices i can confirm that remotely restarting the clients will automaticly update to the new 5.9.3 version. I've done this in the last 10 minutes for 25 devices and they're all running 5.9.3 👍

**Comment by nithiz** [comment]
@welrachid @Ben-Maxfield  Just a heads up: I did notice that some devices running on 5.8.* need two reboots. The first reboot updated the device to 5.9.2, the second reboot updated the device from 5.9.2 to 5.9.3.

**Comment by Ben-Maxfield** [comment]
@nithiz Thanks for the heads up, still waiting for colleague to action...

**Comment by welrachid** [comment]
@nithiz thx. We're not running managed, so I've issued a turn off-turn on to all location personel. Hopefully it should enough. Will have an update tomorrow morning 08.00 (CET)

**Comment by nithiz** [comment]
@welrachid  @Ben-Maxfield @matt-cook Great job guys. Some devices take a little longer to update i noticed, but i think at least everything will be updated within a few hours from now :) I'll give you guys a status update tomorrow.

**Comment by Ben-Maxfield** [comment]
@welrachid @nithiz @matt-cook Can also confirm devices are coming back to life after a reboot, assuming most will auto update over time, but any critical ones we have we can issue a reboot instruction for. Awesome job everyone, thanks!

**Comment by matt-cook** [comment]
Thanks for the quick problem solving guys. Needless to say, this is a situation I'd like to avoid in the future. We'll be looking into additional protections to prevent this sort of problem.

Ideally, I'd like to disable auto-update to folks can roll out updates in a more controlled fashion. Unfortunately, it doesn't sound like this is generally possible on ChromeOS devices. I've had success with Windows-based installations using these instructions: https://www.chromium.org/administrators/turning-off-auto-updates

**Comment by welrachid** [comment]
@matt-cook having multiple apps? like a beta app? or is that not working? then you can be in different channels

**Comment by Ben-Maxfield** [comment]
@matt-cook No problem, impressive turnaround by all so thanks. 

I don't know enough about extensions to offer much input with regard to how to implement such a mechanism, but I do know we have some limited control on our devices using the chrome.exe --extensions-update-frequency flag and also with the steps you have linked, which we may look to as a temporary implementation.

Like @welrachid said, multiple channels could be a good idea but not sure what the take up would be on a beta channel, and if it would be enough to get realistic user testing in a real world environment and therefore justify the additional overhead of managing multiple versions.

**Comment by matt-cook** [comment]
@welrachid beta releases are an excellent idea. The time has probably also come for full unit/regression testing as well. We were able to get by without when it was pretty simple and low-use-age. Would love to hear what make sense for everyone.

cc @ericholmer, @matt-schuh, @nicross at https://github.com/zebradog since you're heavily invested in this.

**Comment by welrachid** [comment]
Hi guys. Just checking in to confirm that units have been updated without any further interference.
Thanks for quick reaction.

**Comment by Ben-Maxfield** [comment]
Also checking in to confirm fix, all good now thanks all

**Comment by allencoin** [comment]
We're good to go here too. I had actually started manually refreshing all of our kiosks when the update went out. Really appreciate the quick turnaround on this problem, @matt-cook!

**Comment by nithiz** [comment]
All good here too, within 12h all kiosks were updated :) Great support @matt-cook. Thanks everyone!
